"use client";
import type { Metadata } from "next";
import Link from "next/link";
import "./styles.css";
import { usePathname } from "next/navigation";  

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const NavLinks = [{
  name: "Register",
  href: "/register"
},
{
  name: "Login",
  href: "/login"
}, {
  name: "Forgot Password:",
  href: "/forgot-password"
}]


export default function RootLayout({



  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <header>
          <div style={{ backgroundColor: "black", color: "white" }}>
            <h1 className="text-red-500 text-5xl">
  Header
</h1>
          </div></header>
        <div>
          {NavLinks.map((link) => {

            const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/");

            return (
              <Link className={isActive ? "font-bold text-blue-500" : "text-gray-500"} 
              key={link.name} href={link.href}>
                {link.name}
              </Link>
            );
          })}
        </div>
        {children}</body>

    </html>
  );
}
